M48
; DRILL file {KiCad 9.0.8} date 2026-04-17T15:35:10-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-17T15:35:10-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X59.465Y-22.38
X64.315Y-22.38
T2
X59.165Y-19.35
X64.615Y-19.35
T3
X22.0Y-67.0
X99.0Y-20.0
X99.0Y-67.0
M30
