M48
; DRILL file {KiCad 9.0.8} date 2026-04-17T15:42:07-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-17T15:42:07-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X53.69Y-22.38
X58.54Y-22.38
T2
X53.39Y-19.35
X58.84Y-19.35
T3
X19.005Y-20.0
X19.005Y-67.0
X96.0Y-20.0
X96.005Y-67.0
M30
